# Code generated by protoc-gen-twirp_ruby, DO NOT EDIT.
require 'twirp'

module Example
  module HelloWorld
    class HelloWorldService < Twirp::Service
      package "example.hello_world"
      service "HelloWorld"
      rpc :Hello, HelloRequest, HelloResponse, :ruby_method => :hello
    end

    class HelloWorldClient < Twirp::Client
      client_for HelloWorldService
    end
  end
end
