# Code generated by protoc-gen-twirp_ruby 1.11.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Example
  module StreamingResponse
    class HelloWorldStreamingService < ::Twirp::Service
      package 'example.streaming_response'
      service 'HelloWorldStreaming'
      rpc :Hello, HelloStreamingRequest, HelloStreamingResponse, :ruby_method => :hello, stream: true # TODO: `stream: true` is manually set, make it part of the codegen.
    end

    class HelloWorldStreamingClient < ::Twirp::Client
      client_for HelloWorldStreamingService
    end
  end
end
