# Code generated by protoc-gen-twirp_ruby 1.11.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Twirp
  module Svc
    class TwirpSvcService < ::Twirp::Service
      package 'twirp.svc'
      service 'TwirpSvc'
      rpc :Hello, HelloSvcRequest, HelloSvcResponse, :ruby_method => :hello
      rpc :HelloStream, HelloSvcRequest, HelloSvcResponse, :ruby_method => :hello_stream, stream: true
    end

    class TwirpSvcClient < ::Twirp::Client
      client_for TwirpSvcService
    end
  end
end
